# Project identification
sonar.projectKey=flask-task-manager
sonar.projectName=Flask Task Manager
sonar.projectVersion=1.0

# Source code location
sonar.sources=app
sonar.tests=tests

# Python settings
sonar.language=py
sonar.python.version=3.11

# Test coverage report
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,instance/**

# Authentication
sonar.host.url=http://sonarqube:9000
sonar.login=squ_983bfb35eb1bf2124ad2f0f5cdb3cd9fde2b2c62

